### ISSUE TITLE
Does it support a complete satis.json?

### ISSUE THREAD

**Issue by andygrunwald** [compotlab/synopsis#1]
Hey,

in the README you say "like satis".
I ask myself if synopsis support a complete satis.json inkl. all settings like dist support?
It is possible to list the supported features or limitations?

**Comment by omosur** [comment]
@andygrunwald I use only some of them, this is my config.json:
`{`
  `"name": "My Repository",`
  `"homepage": "http://packages.example.org",`
  `"archive": {`
    `"directory": "dist",`
    `"skip-dev": false`
  `},`
  `"repositories": []`
`}`

This is all supported params for now. I used this params before, even when i used satis. But if you use something else, i can add them, just tell me.

**Comment by andygrunwald** [comment]
My current statis.json looks like:

``` json
{
    "name": "My Repository",
    "homepage": "http://packages.example.org",
    "require-all": true,
    "require-dependencies": true,
    "archive": {
        "directory": "dist",
        "format": "tar",
        "skip-dev": true
    },
    "repositories": [
        {
            "type": "git",
            ....
```

So `archive.format`, `require-all` and `require-dependencies` support seems to be missing.

**Comment by omosur** [comment]
No, unfortunately, this not supported yet. Archive format only `zip` and `require-*` not supported in full. As soon as possible i'll add this and another main configuration params. I have to update readme so as not confuse people, sorry.

**Comment by omosur** [comment]
Just updated README and fix some satis config params.
